# Generated by Django 5.2.3 on 2025-06-19 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="event",
            name="zip_code",
        ),
    ]
