# Generated by Django 5.2.3 on 2025-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured events will be displayed on the homepage",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_display",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'Free', '-', 'Starting at .99'",
                max_length=100,
            ),
        ),
    ]
