# Generated by Django 5.2.3 on 2025-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_is_featured_alter_event_price_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Special image for the homepage hero section (optional)",
                null=True,
                upload_to="events_hero_images/",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="show_in_hero",
            field=models.BooleanField(
                default=False, help_text="Show this event in the homepage hero section"
            ),
        ),
    ]
