# Generated by Django 5.2.3 on 2025-06-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_hero_image_event_show_in_hero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_published",
        ),
    ]
