# Generated by Django 5.2.3 on 2025-11-29 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_date", "-start_time"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "ordering": ["-subscribed_at"],
                "verbose_name": "Suscriptor del Boletín",
                "verbose_name_plural": "Suscriptores del Boletín",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Clase de icono Bootstrap, ej. 'bi-trophy'",
                max_length=50,
                verbose_name="icono",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="activa"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Orden en el que se debe mostrar la categoría",
                verbose_name="orden",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="events.category",
                verbose_name="categoría padre",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="additional_info",
            field=models.TextField(
                blank=True,
                help_text="Cualquier información adicional sobre el evento",
                verbose_name="información adicional",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(max_length=255, verbose_name="dirección"),
        ),
        migrations.AlterField(
            model_name="event",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="dirección (línea 2)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.category",
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(max_length=100, verbose_name="ciudad"),
        ),
        migrations.AlterField(
            model_name="event",
            name="country",
            field=models.CharField(
                default="España", max_length=100, verbose_name="país"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(verbose_name="fecha de finalización"),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(verbose_name="hora de finalización"),
        ),
        migrations.AlterField(
            model_name="event",
            name="faq",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de elementos de preguntas frecuentes",
                verbose_name="preguntas frecuentes",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events_images/",
                verbose_name="imagen destacada",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Imagen especial para la sección hero de la página principal (opcional)",
                null=True,
                upload_to="events_hero_images/",
                verbose_name="imagen hero",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de URLs de imágenes adicionales",
                verbose_name="galería de imágenes",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Los eventos destacados se mostrarán en la página principal",
                verbose_name="destacado",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="es gratuito"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_name",
            field=models.CharField(max_length=255, verbose_name="nombre del lugar"),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="capacidad máxima"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_description",
            field=models.TextField(
                blank=True, verbose_name="descripción del organizador"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizer_logos/",
                verbose_name="logo del organizador",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(
                max_length=100, verbose_name="nombre del organizador"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price_display",
            field=models.CharField(
                blank=True,
                help_text="ej., 'Gratis', '-', 'Desde .99'",
                max_length=100,
                verbose_name="mostrar precio",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_required",
            field=models.BooleanField(default=False, verbose_name="requiere registro"),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_url",
            field=models.URLField(
                blank=True,
                help_text="URL externa de registro/venta de entradas",
                verbose_name="URL de registro",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Una breve descripción para los listados",
                max_length=200,
                verbose_name="descripción corta",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="show_in_hero",
            field=models.BooleanField(
                default=False,
                help_text="Mostrar este evento en la sección hero de la página principal",
                verbose_name="mostrar en hero",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(verbose_name="fecha de inicio"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(verbose_name="hora de inicio"),
        ),
        migrations.AlterField(
            model_name="event",
            name="state_province",
            field=models.CharField(max_length=100, verbose_name="estado/provincia"),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("cancelled", "Cancelado"),
                    ("ended", "Finalizado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Etiquetas separadas por comas",
                max_length=500,
                verbose_name="etiquetas",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="título"),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue_directions",
            field=models.TextField(
                blank=True,
                help_text="Indicaciones para llegar al lugar, información de estacionamiento, etc.",
                verbose_name="indicaciones del lugar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Enlace al video (YouTube, Vimeo, etc.)",
                verbose_name="URL del video",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si el suscriptor está activo",
                verbose_name="activo",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha de suscripción"
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de cancelación"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="número de orden"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        max_length=254, verbose_name="correo del cliente"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="nombre del cliente"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="teléfono del cliente"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="monto total"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="método de pago"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="referencia de pago"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ej., 'Entrada General', 'VIP', 'Early Bird'",
                        max_length=100,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del tipo de entrada",
                        verbose_name="descripción",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio"
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        help_text="Número total de entradas disponibles",
                        verbose_name="cantidad disponible",
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        default=0, verbose_name="cantidad vendida"
                    ),
                ),
                (
                    "sale_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="inicio de venta"
                    ),
                ),
                (
                    "sale_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fin de venta"
                    ),
                ),
                (
                    "max_per_order",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Número máximo de entradas por orden",
                        verbose_name="máximo por orden",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="orden",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Entrada",
                "verbose_name_plural": "Tipos de Entradas",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="cantidad")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="events.order",
                        verbose_name="orden",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.tickettype",
                        verbose_name="tipo de entrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Orden",
                "verbose_name_plural": "Ítems de Orden",
            },
        ),
    ]
