# Generated by Django 5.2.3 on 2025-12-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_category_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="saved_card_token",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="token de tarjeta guardada"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="used_saved_card",
            field=models.BooleanField(
                default=False, verbose_name="usó tarjeta guardada"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vault_customer_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID del cliente en Vault si se usó tokenización",
                null=True,
                verbose_name="ID de cliente en Vault",
            ),
        ),
        migrations.CreateModel(
            name="CustomerVaultProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="correo del cliente",
                    ),
                ),
                (
                    "vault_customer_id",
                    models.IntegerField(
                        help_text="ID del cliente en la API de Cobalt",
                        verbose_name="ID de cliente en Vault",
                    ),
                ),
                (
                    "vault_reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="referencia de Vault"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "first_surname",
                    models.CharField(max_length=120, verbose_name="primer apellido"),
                ),
                (
                    "second_surname",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="segundo apellido"
                    ),
                ),
                (
                    "doc_id_type",
                    models.CharField(
                        choices=[("C", "Cédula"), ("P", "Pasaporte")],
                        max_length=1,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(max_length=50, verbose_name="número de documento"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Cliente Vault",
                "verbose_name_plural": "Perfiles de Cliente Vault",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_email"], name="events_cust_custome_97e087_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vault_card_id",
                    models.IntegerField(
                        help_text="ID de la tarjeta en la API de Cobalt",
                        verbose_name="ID de tarjeta en Vault",
                    ),
                ),
                (
                    "customer_token",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="token de cliente",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(max_length=20, verbose_name="marca de tarjeta"),
                ),
                (
                    "last_four",
                    models.CharField(max_length=4, verbose_name="últimos 4 dígitos"),
                ),
                (
                    "exp_month",
                    models.CharField(max_length=2, verbose_name="mes de expiración"),
                ),
                (
                    "exp_year",
                    models.CharField(max_length=4, verbose_name="año de expiración"),
                ),
                (
                    "card_holder",
                    models.CharField(max_length=255, verbose_name="titular de tarjeta"),
                ),
                ("alias", models.CharField(max_length=50, verbose_name="alias")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="predeterminada"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último uso"
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to="events.customervaultprofile",
                        verbose_name="perfil de cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Pago Guardado",
                "verbose_name_plural": "Métodos de Pago Guardados",
                "ordering": ["-is_default", "-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_token"], name="events_save_custome_705619_idx"
                    )
                ],
            },
        ),
    ]
