"""
Django settings for event_platform project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-x4t0-q!u=w+mp3#mg7d3q(@w5^5eb(dt(r9_#f1-+!_sg&7i7^")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",  # Unfold admin theme - must be before django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "django_filters",
    "storages",  # django-storages for S3/Spaces
    # My apps
    "events"
]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files efficiently
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Add locale middleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "event_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "static" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # Add media context processor
            ],
        },
    },
]

WSGI_APPLICATION = "event_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Try to get DATABASE_URL from environment (for Heroku, Render, DigitalOcean, etc.)
DATABASE_URL = os.environ.get("DATABASE_URL")

# Validate DATABASE_URL is properly formatted before using it
# This prevents crashes from empty or malformed DATABASE_URL values
if DATABASE_URL and DATABASE_URL.strip() and '://' in DATABASE_URL and not DATABASE_URL.startswith('://'):
    try:
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except Exception as e:
        print(f"⚠️  Warning: Could not parse DATABASE_URL: {e}")
        print(f"   Falling back to default SQLite database")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
else:
    # Use SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Available languages
from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
]

# Location of translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Using /assets/ instead of /static/ to avoid conflict with DigitalOcean ingress rules
STATIC_URL = "/assets/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional static files directories
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Use standard Django storage - WhiteNoise middleware will handle serving
# Don't use WhiteNoise's storage class as it can cause issues
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# WhiteNoise configuration
# In production, WhiteNoise serves files from STATIC_ROOT
# It will also serve files from STATICFILES_DIRS in development
WHITENOISE_USE_FINDERS = DEBUG  # Only use finders in development

# Media files (User uploaded files)
# DigitalOcean Spaces Configuration (S3-compatible object storage)
# Set these environment variables in DigitalOcean App Platform to enable persistent media storage
AWS_ACCESS_KEY_ID = os.environ.get("SPACES_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.environ.get("SPACES_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("SPACES_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("SPACES_REGION", "nyc3")
AWS_S3_ENDPOINT_URL = os.environ.get("SPACES_ENDPOINT_URL")  # e.g., https://nyc3.digitaloceanspaces.com
AWS_S3_CUSTOM_DOMAIN = os.environ.get("SPACES_CDN_DOMAIN")  # e.g., your-bucket.nyc3.cdn.digitaloceanspaces.com

# Use DigitalOcean Spaces for media if configured, otherwise use local storage
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME and AWS_S3_ENDPOINT_URL:
    # S3/Spaces settings
    AWS_DEFAULT_ACL = "public-read"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",  # 1 day cache
    }
    AWS_LOCATION = "media"
    AWS_QUERYSTRING_AUTH = False  # Don't add auth params to URLs (makes them public)
    
    # Use S3 storage for media files
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    
    # Media URL - use CDN domain if available, otherwise construct from endpoint
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    else:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/"
    
    # No local MEDIA_ROOT needed when using Spaces
    MEDIA_ROOT = None
    
    print("✅ Using DigitalOcean Spaces for media storage")
else:
    # Local file storage (for development)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    
    # Create media directory if it doesn't exist
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    
    if not DEBUG:
        print("⚠️  Warning: Using local media storage in production. Files will be lost on deployment!")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "PassClub Admin",
    "SITE_HEADER": "PassClub",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": None,
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": None,
    "DASHBOARD_CALLBACK": None,
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
    # Add custom CSS to fix input field borders
    "STYLES": [
        {
            "source": "/assets/admin/css/admin_custom.css",
        },
    ],
}

# Login redirect settings
LOGIN_REDIRECT_URL = "/dashboard/"
LOGIN_URL = "/dashboard/login/"

# Security settings for production
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
